[test] frontend node_module 절대경로로 2

diff --git a/frontend/Jenkinsfile b/frontend/Jenkinsfile
--- a/frontend/Jenkinsfile
+++ b/frontend/Jenkinsfile
@@ -15,13 +15,14 @@ pipeline {
         stage('Build') {
             steps {
                 sh '''
+                    set -x
                     echo "Current directory: $(pwd)"
                     echo "Files in directory:"
                     ls -la
                     echo "Environment file content:"
                     cat /home/ubuntu/frontend/.env.production
                     echo "Starting build..."
-                    chmod +x /home/ubuntu/frontend/node_modules/vite/bin/vite.js
+                    chmod +x /home/ubuntu/frontend/node_modules/vite/bin/vite.js || echo "vite.js not found"
                     rm -rf /home/ubuntu/frontend/node_modules
                     rm /home/ubuntu/frontend/package-lock.json
                     cd /home/ubuntu/frontend && npm install @rollup/rollup-linux-x64-gnu --save-optional
@@ -29,6 +30,7 @@ pipeline {
                 '''
             }
         }
+
 
         stage('Deploy') {
             steps {
